eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8086
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: search
        predicates:
        - Path=/search/**
        uri: lb://search-service/search
      - id: book
        predicates:
        - Path=/book/**
        uri: lb://Flight-Service/book
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE